### PR TITLE
Qt 5.11 beta: CMakeLists.txt: Fix FTBFS (dropping qt5_use_modules)

### PR DESCRIPTION
**Pull request by MaxKrummenacher**
| CMake Error at .../CMakeLists.txt (qt5_use_modules):
|   Unknown CMake command "qt5_use_modules".

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>

### CODE REVIEW

**Comment by agaida** [comment]
refs lxqt/lxqt/issues/1487

**Comment by tsujan** [comment]
Any probable change should be compatible with Qt < 5.11

**Comment by Dessa** [comment]
more about it here: http://lists.qt-project.org/pipermail/development/2018-June/032837.html

so short version: they restored the macro for 5.11.1.

but to be fair i don't see why this should be incompatible with qt < 5.11

**Comment by agaida** [comment]
Right

**Pull request merged**
