### PR TITLE
Rename strings.cpp and strings.h to appletstrings.cpp and appletstrin…

### PR DESCRIPTION
**Pull request by gabretana**
This solve #17 , thanks to @yan12125

### CODE REVIEW

**Review by yan12125 — APPROVED** [review]
LGTM. I'd like to wait for another developer who uses this tool often before merging.

**Comment by logol** [comment]
please merge :+1:

**Review by jwldr — APPROVED** [review]
:+1: please merge it

**Comment by yan12125** [comment]
This looks good so I'll merge it first. If it brings any regression, please open a new issue, thanks!

**Pull request merged**
